### ISSUE TITLE
Error: Could not find or load main class com.ka.spreadsheet.diff.SpreadSheetDiffer

### ISSUE THREAD

**Issue by operations-ivy** [na-ka-na/ExcelCompare#15]
Getting this error when attempting to run the script:
Error: Could not find or load main class com.ka.spreadsheet.diff.SpreadSheetDiffer

Ran it as sudo and got the following stack trace: 

Exception in thread "main" java.lang.NoClassDefFoundError: com/ka/spreadsheet/diff/SpreadSheetDiffer
Caused by: java.lang.ClassNotFoundException: com.ka.spreadsheet.diff.SpreadSheetDiffer
    at java.net.URLClassLoader$1.run(URLClassLoader.java:217)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:323)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:294)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:268)

The command I'm using is pretty simple:

$ excel_cmp file_one.xls file_two.xls

ran it within the path where the java file in the error is held and got the same results

**Comment by t3rmina1** [comment]
I'm having the same issue. I'm running it as:

excel_cmp file_one.xls file_two.xls

Exception in thread "main" java.lang.NoClassDefFoundError: com/ka/spreadsheet/diff/SpreadSheetDiffer
Caused by: java.lang.ClassNotFoundException: com.ka.spreadsheet.diff.SpreadSheet
Differ
        at java.net.URLClassLoader$1.run(URLClassLoader.java:200)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:188)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:307)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:252)
        at java.lang.ClassLoader.loadClassInternal(ClassLoader.java:320)
Could not find the main class: com.ka.spreadsheet.diff.SpreadSheetDiffer.  Program will exit.

I'm using the zip

**Comment by na-ka-na** [comment]
you might have downloaded the source .. download the binary from here https://github.com/na-ka-na/ExcelCompare/releases

**Comment by t3rmina1** [comment]
Hi there, thanks for your help, it was my own error.
