### ISSUE TITLE
Out of memory error

### ISSUE THREAD

**Issue by jonnyijapan** [na-ka-na/ExcelCompare#17]
I have two sheets that are pretty big. Around 6 MB each. When comparing them, this is what happens:

```
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.util.ArrayList.<init>(ArrayList.java:132)
	at java.util.ArrayList.<init>(ArrayList.java:139)
	at org.apache.xmlbeans.impl.values.NamespaceContext$NamespaceContextStack.<init>(NamespaceContext.java:78)
	at org.apache.xmlbeans.impl.values.NamespaceContext$NamespaceContextStack.<init>(NamespaceContext.java:75)
	at org.apache.xmlbeans.impl.values.NamespaceContext.getNamespaceContextStack(NamespaceContext.java:98)
	at org.apache.xmlbeans.impl.values.NamespaceContext.push(NamespaceContext.java:106)
	at org.apache.xmlbeans.impl.values.XmlObjectBase.check_dated(XmlObjectBase.java:1273)
	at org.apache.xmlbeans.impl.values.XmlObjectBase.stringValue(XmlObjectBase.java:1484)
	at org.apache.xmlbeans.impl.values.XmlObjectBase.getStringValue(XmlObjectBase.java:1492)
	at org.openxmlformats.schemas.spreadsheetml.x2006.main.impl.CTCellImpl.getR(Unknown Source)
	at org.apache.poi.xssf.usermodel.XSSFCell.<init>(XSSFCell.java:105)
	at org.apache.poi.xssf.usermodel.XSSFRow.<init>(XSSFRow.java:70)
	at org.apache.poi.xssf.usermodel.XSSFSheet.initRows(XSSFSheet.java:179)
	at org.apache.poi.xssf.usermodel.XSSFSheet.read(XSSFSheet.java:143)
	at org.apache.poi.xssf.usermodel.XSSFSheet.onDocumentRead(XSSFSheet.java:130)
	at org.apache.poi.xssf.usermodel.XSSFWorkbook.onDocumentRead(XSSFWorkbook.java:286)
	at org.apache.poi.POIXMLDocument.load(POIXMLDocument.java:159)
	at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:186)
	at org.apache.poi.ss.usermodel.WorkbookFactory.create(WorkbookFactory.java:91)
	at com.ka.spreadsheet.diff.SpreadSheetDiffer.loadSpreadSheet(SpreadSheetDiffer.java:162)
	at com.ka.spreadsheet.diff.SpreadSheetDiffer.doDiff(SpreadSheetDiffer.java:81)
	at com.ka.spreadsheet.diff.SpreadSheetDiffer.doDiff(SpreadSheetDiffer.java:61)
	at com.ka.spreadsheet.diff.SpreadSheetDiffer.main(SpreadSheetDiffer.java:54)
```

**Comment by na-ka-na** [comment]
Increase the heap ram.. it it set to 512m by default. Open your excel_cmp script and change the -Xmx512m flag to something like -Xmx2g (to make in 2 gb).
