### ISSUE TITLE
I can't use your software

### ISSUE THREAD

**Issue by zhanghang25** [na-ka-na/ExcelCompare#43]
my operation system is windows 10 . And i follow your advice to set,but It's not use.
I use the eclipse ee to run your program but miss jar.
so about these two problem，what should I do.

**Comment by na-ka-na** [comment]
in the release download, i have a bunch of jars. You have to add all those jars to your eclipse classpath. Then run the main program SpreadSheetDiffer with the two files.

**Comment by zhanghang25** [comment]
what‘s your release download。i just download your zip file and i don't find your jar files.
i am a new man ,please show me the approach.
Best wishes to you.

**Comment by zhanghang25** [comment]
my windows system can not work your bat file,and i have also import all the jar files ,I comfirm it.
what's wrong with me ?

**Comment by zhanghang25** [comment]
my windows .bat script can't work ,what's wrong with me ?
it's just said "can't find or load the main class  com.ka.spreadsheet.diff.SpreadSheetDiffer

**Comment by zhanghang25** [comment]
`Identical xlsx files... Exception in thread "main" java.io.FileNotFoundException: win_test\resources\ss1_xlsx_ss1_xlsx.out (系统找不到指定的路径。)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at java.io.FileReader.<init>(Unknown Source)
	at com.ka.spreadsheet.diff.TestUtils.readFileIntoLines(TestUtils.java:34)
	at com.ka.spreadsheet.diff.TestUtils.verifyFileContentsSame(TestUtils.java:21)
	at com.ka.spreadsheet.diff.SpreadSheetDifferSmokeTest.testDiff(SpreadSheetDifferSmokeTest.java:171)
	at com.ka.spreadsheet.diff.SpreadSheetDifferSmokeTest.main(SpreadSheetDifferSmokeTest.java:18)
`
this is my error report in my console
